
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Status = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  ARCHIVED: 'ARCHIVED'
} as const

export type Status = (typeof Status)[keyof typeof Status]


export const RoleType = {
  ADMIN: 'ADMIN',
  USER: 'USER',
  GUEST: 'GUEST'
} as const

export type RoleType = (typeof RoleType)[keyof typeof RoleType]


export const PermissionType = {
  READ: 'READ',
  WRITE: 'WRITE',
  DELETE: 'DELETE'
} as const

export type PermissionType = (typeof PermissionType)[keyof typeof PermissionType]


export const AuditType = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  DATA_CHANGE: 'DATA_CHANGE',
  PERMISSION_CHANGE: 'PERMISSION_CHANGE'
} as const

export type AuditType = (typeof AuditType)[keyof typeof AuditType]


export const ReportType = {
  BUG: 'BUG',
  FEATURE_REQUEST: 'FEATURE_REQUEST',
  OTHER: 'OTHER',
  REPORT: 'REPORT',
  ANALYTICS: 'ANALYTICS',
  QUALITY: 'QUALITY',
  QUANTITY: 'QUANTITY'
} as const

export type ReportType = (typeof ReportType)[keyof typeof ReportType]


export const ContactType = {
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  SOCIAL: 'SOCIAL'
} as const

export type ContactType = (typeof ContactType)[keyof typeof ContactType]


export const AddressType = {
  HOME: 'HOME',
  WORK: 'WORK'
} as const

export type AddressType = (typeof AddressType)[keyof typeof AddressType]
