
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Audit` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Audit
 * 
 */
export type AuditModel = runtime.Types.Result.DefaultSelection<Prisma.$AuditPayload>

export type AggregateAudit = {
  _count: AuditCountAggregateOutputType | null
  _min: AuditMinAggregateOutputType | null
  _max: AuditMaxAggregateOutputType | null
}

export type AuditMinAggregateOutputType = {
  id: string | null
  userId: string | null
  type: $Enums.AuditType | null
  action: string | null
  entity: string | null
  entityId: string | null
  before: string | null
  after: string | null
  createdAt: Date | null
}

export type AuditMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  type: $Enums.AuditType | null
  action: string | null
  entity: string | null
  entityId: string | null
  before: string | null
  after: string | null
  createdAt: Date | null
}

export type AuditCountAggregateOutputType = {
  id: number
  userId: number
  type: number
  action: number
  entity: number
  entityId: number
  before: number
  after: number
  createdAt: number
  _all: number
}


export type AuditMinAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  action?: true
  entity?: true
  entityId?: true
  before?: true
  after?: true
  createdAt?: true
}

export type AuditMaxAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  action?: true
  entity?: true
  entityId?: true
  before?: true
  after?: true
  createdAt?: true
}

export type AuditCountAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  action?: true
  entity?: true
  entityId?: true
  before?: true
  after?: true
  createdAt?: true
  _all?: true
}

export type AuditAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Audit to aggregate.
   */
  where?: Prisma.AuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Audits to fetch.
   */
  orderBy?: Prisma.AuditOrderByWithRelationInput | Prisma.AuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Audits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Audits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Audits
  **/
  _count?: true | AuditCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AuditMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AuditMaxAggregateInputType
}

export type GetAuditAggregateType<T extends AuditAggregateArgs> = {
      [P in keyof T & keyof AggregateAudit]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAudit[P]>
    : Prisma.GetScalarType<T[P], AggregateAudit[P]>
}




export type AuditGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuditWhereInput
  orderBy?: Prisma.AuditOrderByWithAggregationInput | Prisma.AuditOrderByWithAggregationInput[]
  by: Prisma.AuditScalarFieldEnum[] | Prisma.AuditScalarFieldEnum
  having?: Prisma.AuditScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AuditCountAggregateInputType | true
  _min?: AuditMinAggregateInputType
  _max?: AuditMaxAggregateInputType
}

export type AuditGroupByOutputType = {
  id: string
  userId: string
  type: $Enums.AuditType
  action: string
  entity: string
  entityId: string | null
  before: string | null
  after: string | null
  createdAt: Date
  _count: AuditCountAggregateOutputType | null
  _min: AuditMinAggregateOutputType | null
  _max: AuditMaxAggregateOutputType | null
}

export type GetAuditGroupByPayload<T extends AuditGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AuditGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AuditGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AuditGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AuditGroupByOutputType[P]>
      }
    >
  >



export type AuditWhereInput = {
  AND?: Prisma.AuditWhereInput | Prisma.AuditWhereInput[]
  OR?: Prisma.AuditWhereInput[]
  NOT?: Prisma.AuditWhereInput | Prisma.AuditWhereInput[]
  id?: Prisma.UuidFilter<"Audit"> | string
  userId?: Prisma.UuidFilter<"Audit"> | string
  type?: Prisma.EnumAuditTypeFilter<"Audit"> | $Enums.AuditType
  action?: Prisma.StringFilter<"Audit"> | string
  entity?: Prisma.StringFilter<"Audit"> | string
  entityId?: Prisma.StringNullableFilter<"Audit"> | string | null
  before?: Prisma.StringNullableFilter<"Audit"> | string | null
  after?: Prisma.StringNullableFilter<"Audit"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Audit"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type AuditOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  action?: Prisma.SortOrder
  entity?: Prisma.SortOrder
  entityId?: Prisma.SortOrderInput | Prisma.SortOrder
  before?: Prisma.SortOrderInput | Prisma.SortOrder
  after?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type AuditWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AuditWhereInput | Prisma.AuditWhereInput[]
  OR?: Prisma.AuditWhereInput[]
  NOT?: Prisma.AuditWhereInput | Prisma.AuditWhereInput[]
  userId?: Prisma.UuidFilter<"Audit"> | string
  type?: Prisma.EnumAuditTypeFilter<"Audit"> | $Enums.AuditType
  action?: Prisma.StringFilter<"Audit"> | string
  entity?: Prisma.StringFilter<"Audit"> | string
  entityId?: Prisma.StringNullableFilter<"Audit"> | string | null
  before?: Prisma.StringNullableFilter<"Audit"> | string | null
  after?: Prisma.StringNullableFilter<"Audit"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Audit"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type AuditOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  action?: Prisma.SortOrder
  entity?: Prisma.SortOrder
  entityId?: Prisma.SortOrderInput | Prisma.SortOrder
  before?: Prisma.SortOrderInput | Prisma.SortOrder
  after?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AuditCountOrderByAggregateInput
  _max?: Prisma.AuditMaxOrderByAggregateInput
  _min?: Prisma.AuditMinOrderByAggregateInput
}

export type AuditScalarWhereWithAggregatesInput = {
  AND?: Prisma.AuditScalarWhereWithAggregatesInput | Prisma.AuditScalarWhereWithAggregatesInput[]
  OR?: Prisma.AuditScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AuditScalarWhereWithAggregatesInput | Prisma.AuditScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Audit"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"Audit"> | string
  type?: Prisma.EnumAuditTypeWithAggregatesFilter<"Audit"> | $Enums.AuditType
  action?: Prisma.StringWithAggregatesFilter<"Audit"> | string
  entity?: Prisma.StringWithAggregatesFilter<"Audit"> | string
  entityId?: Prisma.StringNullableWithAggregatesFilter<"Audit"> | string | null
  before?: Prisma.StringNullableWithAggregatesFilter<"Audit"> | string | null
  after?: Prisma.StringNullableWithAggregatesFilter<"Audit"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Audit"> | Date | string
}

export type AuditCreateInput = {
  id?: string
  type: $Enums.AuditType
  action: string
  entity: string
  entityId?: string | null
  before?: string | null
  after?: string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAuditsInput
}

export type AuditUncheckedCreateInput = {
  id?: string
  userId: string
  type: $Enums.AuditType
  action: string
  entity: string
  entityId?: string | null
  before?: string | null
  after?: string | null
  createdAt?: Date | string
}

export type AuditUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAuditTypeFieldUpdateOperationsInput | $Enums.AuditType
  action?: Prisma.StringFieldUpdateOperationsInput | string
  entity?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  before?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  after?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAuditsNestedInput
}

export type AuditUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAuditTypeFieldUpdateOperationsInput | $Enums.AuditType
  action?: Prisma.StringFieldUpdateOperationsInput | string
  entity?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  before?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  after?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuditCreateManyInput = {
  id?: string
  userId: string
  type: $Enums.AuditType
  action: string
  entity: string
  entityId?: string | null
  before?: string | null
  after?: string | null
  createdAt?: Date | string
}

export type AuditUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAuditTypeFieldUpdateOperationsInput | $Enums.AuditType
  action?: Prisma.StringFieldUpdateOperationsInput | string
  entity?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  before?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  after?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuditUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAuditTypeFieldUpdateOperationsInput | $Enums.AuditType
  action?: Prisma.StringFieldUpdateOperationsInput | string
  entity?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  before?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  after?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuditCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  action?: Prisma.SortOrder
  entity?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  before?: Prisma.SortOrder
  after?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuditMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  action?: Prisma.SortOrder
  entity?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  before?: Prisma.SortOrder
  after?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuditMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  action?: Prisma.SortOrder
  entity?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  before?: Prisma.SortOrder
  after?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuditListRelationFilter = {
  every?: Prisma.AuditWhereInput
  some?: Prisma.AuditWhereInput
  none?: Prisma.AuditWhereInput
}

export type AuditOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EnumAuditTypeFieldUpdateOperationsInput = {
  set?: $Enums.AuditType
}

export type AuditCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AuditCreateWithoutUserInput, Prisma.AuditUncheckedCreateWithoutUserInput> | Prisma.AuditCreateWithoutUserInput[] | Prisma.AuditUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AuditCreateOrConnectWithoutUserInput | Prisma.AuditCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AuditCreateManyUserInputEnvelope
  connect?: Prisma.AuditWhereUniqueInput | Prisma.AuditWhereUniqueInput[]
}

export type AuditUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AuditCreateWithoutUserInput, Prisma.AuditUncheckedCreateWithoutUserInput> | Prisma.AuditCreateWithoutUserInput[] | Prisma.AuditUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AuditCreateOrConnectWithoutUserInput | Prisma.AuditCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AuditCreateManyUserInputEnvelope
  connect?: Prisma.AuditWhereUniqueInput | Prisma.AuditWhereUniqueInput[]
}

export type AuditUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AuditCreateWithoutUserInput, Prisma.AuditUncheckedCreateWithoutUserInput> | Prisma.AuditCreateWithoutUserInput[] | Prisma.AuditUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AuditCreateOrConnectWithoutUserInput | Prisma.AuditCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AuditUpsertWithWhereUniqueWithoutUserInput | Prisma.AuditUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AuditCreateManyUserInputEnvelope
  set?: Prisma.AuditWhereUniqueInput | Prisma.AuditWhereUniqueInput[]
  disconnect?: Prisma.AuditWhereUniqueInput | Prisma.AuditWhereUniqueInput[]
  delete?: Prisma.AuditWhereUniqueInput | Prisma.AuditWhereUniqueInput[]
  connect?: Prisma.AuditWhereUniqueInput | Prisma.AuditWhereUniqueInput[]
  update?: Prisma.AuditUpdateWithWhereUniqueWithoutUserInput | Prisma.AuditUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AuditUpdateManyWithWhereWithoutUserInput | Prisma.AuditUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AuditScalarWhereInput | Prisma.AuditScalarWhereInput[]
}

export type AuditUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AuditCreateWithoutUserInput, Prisma.AuditUncheckedCreateWithoutUserInput> | Prisma.AuditCreateWithoutUserInput[] | Prisma.AuditUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AuditCreateOrConnectWithoutUserInput | Prisma.AuditCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AuditUpsertWithWhereUniqueWithoutUserInput | Prisma.AuditUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AuditCreateManyUserInputEnvelope
  set?: Prisma.AuditWhereUniqueInput | Prisma.AuditWhereUniqueInput[]
  disconnect?: Prisma.AuditWhereUniqueInput | Prisma.AuditWhereUniqueInput[]
  delete?: Prisma.AuditWhereUniqueInput | Prisma.AuditWhereUniqueInput[]
  connect?: Prisma.AuditWhereUniqueInput | Prisma.AuditWhereUniqueInput[]
  update?: Prisma.AuditUpdateWithWhereUniqueWithoutUserInput | Prisma.AuditUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AuditUpdateManyWithWhereWithoutUserInput | Prisma.AuditUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AuditScalarWhereInput | Prisma.AuditScalarWhereInput[]
}

export type AuditCreateWithoutUserInput = {
  id?: string
  type: $Enums.AuditType
  action: string
  entity: string
  entityId?: string | null
  before?: string | null
  after?: string | null
  createdAt?: Date | string
}

export type AuditUncheckedCreateWithoutUserInput = {
  id?: string
  type: $Enums.AuditType
  action: string
  entity: string
  entityId?: string | null
  before?: string | null
  after?: string | null
  createdAt?: Date | string
}

export type AuditCreateOrConnectWithoutUserInput = {
  where: Prisma.AuditWhereUniqueInput
  create: Prisma.XOR<Prisma.AuditCreateWithoutUserInput, Prisma.AuditUncheckedCreateWithoutUserInput>
}

export type AuditCreateManyUserInputEnvelope = {
  data: Prisma.AuditCreateManyUserInput | Prisma.AuditCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AuditUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AuditWhereUniqueInput
  update: Prisma.XOR<Prisma.AuditUpdateWithoutUserInput, Prisma.AuditUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AuditCreateWithoutUserInput, Prisma.AuditUncheckedCreateWithoutUserInput>
}

export type AuditUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AuditWhereUniqueInput
  data: Prisma.XOR<Prisma.AuditUpdateWithoutUserInput, Prisma.AuditUncheckedUpdateWithoutUserInput>
}

export type AuditUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AuditScalarWhereInput
  data: Prisma.XOR<Prisma.AuditUpdateManyMutationInput, Prisma.AuditUncheckedUpdateManyWithoutUserInput>
}

export type AuditScalarWhereInput = {
  AND?: Prisma.AuditScalarWhereInput | Prisma.AuditScalarWhereInput[]
  OR?: Prisma.AuditScalarWhereInput[]
  NOT?: Prisma.AuditScalarWhereInput | Prisma.AuditScalarWhereInput[]
  id?: Prisma.UuidFilter<"Audit"> | string
  userId?: Prisma.UuidFilter<"Audit"> | string
  type?: Prisma.EnumAuditTypeFilter<"Audit"> | $Enums.AuditType
  action?: Prisma.StringFilter<"Audit"> | string
  entity?: Prisma.StringFilter<"Audit"> | string
  entityId?: Prisma.StringNullableFilter<"Audit"> | string | null
  before?: Prisma.StringNullableFilter<"Audit"> | string | null
  after?: Prisma.StringNullableFilter<"Audit"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Audit"> | Date | string
}

export type AuditCreateManyUserInput = {
  id?: string
  type: $Enums.AuditType
  action: string
  entity: string
  entityId?: string | null
  before?: string | null
  after?: string | null
  createdAt?: Date | string
}

export type AuditUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAuditTypeFieldUpdateOperationsInput | $Enums.AuditType
  action?: Prisma.StringFieldUpdateOperationsInput | string
  entity?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  before?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  after?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuditUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAuditTypeFieldUpdateOperationsInput | $Enums.AuditType
  action?: Prisma.StringFieldUpdateOperationsInput | string
  entity?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  before?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  after?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuditUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAuditTypeFieldUpdateOperationsInput | $Enums.AuditType
  action?: Prisma.StringFieldUpdateOperationsInput | string
  entity?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  before?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  after?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AuditSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  action?: boolean
  entity?: boolean
  entityId?: boolean
  before?: boolean
  after?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["audit"]>

export type AuditSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  action?: boolean
  entity?: boolean
  entityId?: boolean
  before?: boolean
  after?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["audit"]>

export type AuditSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  action?: boolean
  entity?: boolean
  entityId?: boolean
  before?: boolean
  after?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["audit"]>

export type AuditSelectScalar = {
  id?: boolean
  userId?: boolean
  type?: boolean
  action?: boolean
  entity?: boolean
  entityId?: boolean
  before?: boolean
  after?: boolean
  createdAt?: boolean
}

export type AuditOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "type" | "action" | "entity" | "entityId" | "before" | "after" | "createdAt", ExtArgs["result"]["audit"]>
export type AuditInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AuditIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AuditIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AuditPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Audit"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    type: $Enums.AuditType
    action: string
    entity: string
    entityId: string | null
    before: string | null
    after: string | null
    createdAt: Date
  }, ExtArgs["result"]["audit"]>
  composites: {}
}

export type AuditGetPayload<S extends boolean | null | undefined | AuditDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AuditPayload, S>

export type AuditCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AuditFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AuditCountAggregateInputType | true
  }

export interface AuditDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Audit'], meta: { name: 'Audit' } }
  /**
   * Find zero or one Audit that matches the filter.
   * @param {AuditFindUniqueArgs} args - Arguments to find a Audit
   * @example
   * // Get one Audit
   * const audit = await prisma.audit.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AuditFindUniqueArgs>(args: Prisma.SelectSubset<T, AuditFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AuditClient<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Audit that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AuditFindUniqueOrThrowArgs} args - Arguments to find a Audit
   * @example
   * // Get one Audit
   * const audit = await prisma.audit.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AuditFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AuditFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuditClient<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Audit that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuditFindFirstArgs} args - Arguments to find a Audit
   * @example
   * // Get one Audit
   * const audit = await prisma.audit.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AuditFindFirstArgs>(args?: Prisma.SelectSubset<T, AuditFindFirstArgs<ExtArgs>>): Prisma.Prisma__AuditClient<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Audit that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuditFindFirstOrThrowArgs} args - Arguments to find a Audit
   * @example
   * // Get one Audit
   * const audit = await prisma.audit.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AuditFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AuditFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuditClient<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Audits that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuditFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Audits
   * const audits = await prisma.audit.findMany()
   * 
   * // Get first 10 Audits
   * const audits = await prisma.audit.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const auditWithIdOnly = await prisma.audit.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AuditFindManyArgs>(args?: Prisma.SelectSubset<T, AuditFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Audit.
   * @param {AuditCreateArgs} args - Arguments to create a Audit.
   * @example
   * // Create one Audit
   * const Audit = await prisma.audit.create({
   *   data: {
   *     // ... data to create a Audit
   *   }
   * })
   * 
   */
  create<T extends AuditCreateArgs>(args: Prisma.SelectSubset<T, AuditCreateArgs<ExtArgs>>): Prisma.Prisma__AuditClient<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Audits.
   * @param {AuditCreateManyArgs} args - Arguments to create many Audits.
   * @example
   * // Create many Audits
   * const audit = await prisma.audit.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AuditCreateManyArgs>(args?: Prisma.SelectSubset<T, AuditCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Audits and returns the data saved in the database.
   * @param {AuditCreateManyAndReturnArgs} args - Arguments to create many Audits.
   * @example
   * // Create many Audits
   * const audit = await prisma.audit.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Audits and only return the `id`
   * const auditWithIdOnly = await prisma.audit.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AuditCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AuditCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Audit.
   * @param {AuditDeleteArgs} args - Arguments to delete one Audit.
   * @example
   * // Delete one Audit
   * const Audit = await prisma.audit.delete({
   *   where: {
   *     // ... filter to delete one Audit
   *   }
   * })
   * 
   */
  delete<T extends AuditDeleteArgs>(args: Prisma.SelectSubset<T, AuditDeleteArgs<ExtArgs>>): Prisma.Prisma__AuditClient<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Audit.
   * @param {AuditUpdateArgs} args - Arguments to update one Audit.
   * @example
   * // Update one Audit
   * const audit = await prisma.audit.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AuditUpdateArgs>(args: Prisma.SelectSubset<T, AuditUpdateArgs<ExtArgs>>): Prisma.Prisma__AuditClient<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Audits.
   * @param {AuditDeleteManyArgs} args - Arguments to filter Audits to delete.
   * @example
   * // Delete a few Audits
   * const { count } = await prisma.audit.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AuditDeleteManyArgs>(args?: Prisma.SelectSubset<T, AuditDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Audits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuditUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Audits
   * const audit = await prisma.audit.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AuditUpdateManyArgs>(args: Prisma.SelectSubset<T, AuditUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Audits and returns the data updated in the database.
   * @param {AuditUpdateManyAndReturnArgs} args - Arguments to update many Audits.
   * @example
   * // Update many Audits
   * const audit = await prisma.audit.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Audits and only return the `id`
   * const auditWithIdOnly = await prisma.audit.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AuditUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AuditUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Audit.
   * @param {AuditUpsertArgs} args - Arguments to update or create a Audit.
   * @example
   * // Update or create a Audit
   * const audit = await prisma.audit.upsert({
   *   create: {
   *     // ... data to create a Audit
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Audit we want to update
   *   }
   * })
   */
  upsert<T extends AuditUpsertArgs>(args: Prisma.SelectSubset<T, AuditUpsertArgs<ExtArgs>>): Prisma.Prisma__AuditClient<runtime.Types.Result.GetResult<Prisma.$AuditPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Audits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuditCountArgs} args - Arguments to filter Audits to count.
   * @example
   * // Count the number of Audits
   * const count = await prisma.audit.count({
   *   where: {
   *     // ... the filter for the Audits we want to count
   *   }
   * })
  **/
  count<T extends AuditCountArgs>(
    args?: Prisma.Subset<T, AuditCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AuditCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Audit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuditAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AuditAggregateArgs>(args: Prisma.Subset<T, AuditAggregateArgs>): Prisma.PrismaPromise<GetAuditAggregateType<T>>

  /**
   * Group by Audit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuditGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AuditGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AuditGroupByArgs['orderBy'] }
      : { orderBy?: AuditGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AuditGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuditGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Audit model
 */
readonly fields: AuditFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Audit.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AuditClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Audit model
 */
export interface AuditFieldRefs {
  readonly id: Prisma.FieldRef<"Audit", 'String'>
  readonly userId: Prisma.FieldRef<"Audit", 'String'>
  readonly type: Prisma.FieldRef<"Audit", 'AuditType'>
  readonly action: Prisma.FieldRef<"Audit", 'String'>
  readonly entity: Prisma.FieldRef<"Audit", 'String'>
  readonly entityId: Prisma.FieldRef<"Audit", 'String'>
  readonly before: Prisma.FieldRef<"Audit", 'String'>
  readonly after: Prisma.FieldRef<"Audit", 'String'>
  readonly createdAt: Prisma.FieldRef<"Audit", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Audit findUnique
 */
export type AuditFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditInclude<ExtArgs> | null
  /**
   * Filter, which Audit to fetch.
   */
  where: Prisma.AuditWhereUniqueInput
}

/**
 * Audit findUniqueOrThrow
 */
export type AuditFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditInclude<ExtArgs> | null
  /**
   * Filter, which Audit to fetch.
   */
  where: Prisma.AuditWhereUniqueInput
}

/**
 * Audit findFirst
 */
export type AuditFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditInclude<ExtArgs> | null
  /**
   * Filter, which Audit to fetch.
   */
  where?: Prisma.AuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Audits to fetch.
   */
  orderBy?: Prisma.AuditOrderByWithRelationInput | Prisma.AuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Audits.
   */
  cursor?: Prisma.AuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Audits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Audits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Audits.
   */
  distinct?: Prisma.AuditScalarFieldEnum | Prisma.AuditScalarFieldEnum[]
}

/**
 * Audit findFirstOrThrow
 */
export type AuditFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditInclude<ExtArgs> | null
  /**
   * Filter, which Audit to fetch.
   */
  where?: Prisma.AuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Audits to fetch.
   */
  orderBy?: Prisma.AuditOrderByWithRelationInput | Prisma.AuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Audits.
   */
  cursor?: Prisma.AuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Audits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Audits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Audits.
   */
  distinct?: Prisma.AuditScalarFieldEnum | Prisma.AuditScalarFieldEnum[]
}

/**
 * Audit findMany
 */
export type AuditFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditInclude<ExtArgs> | null
  /**
   * Filter, which Audits to fetch.
   */
  where?: Prisma.AuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Audits to fetch.
   */
  orderBy?: Prisma.AuditOrderByWithRelationInput | Prisma.AuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Audits.
   */
  cursor?: Prisma.AuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Audits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Audits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Audits.
   */
  distinct?: Prisma.AuditScalarFieldEnum | Prisma.AuditScalarFieldEnum[]
}

/**
 * Audit create
 */
export type AuditCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditInclude<ExtArgs> | null
  /**
   * The data needed to create a Audit.
   */
  data: Prisma.XOR<Prisma.AuditCreateInput, Prisma.AuditUncheckedCreateInput>
}

/**
 * Audit createMany
 */
export type AuditCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Audits.
   */
  data: Prisma.AuditCreateManyInput | Prisma.AuditCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Audit createManyAndReturn
 */
export type AuditCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * The data used to create many Audits.
   */
  data: Prisma.AuditCreateManyInput | Prisma.AuditCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Audit update
 */
export type AuditUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditInclude<ExtArgs> | null
  /**
   * The data needed to update a Audit.
   */
  data: Prisma.XOR<Prisma.AuditUpdateInput, Prisma.AuditUncheckedUpdateInput>
  /**
   * Choose, which Audit to update.
   */
  where: Prisma.AuditWhereUniqueInput
}

/**
 * Audit updateMany
 */
export type AuditUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Audits.
   */
  data: Prisma.XOR<Prisma.AuditUpdateManyMutationInput, Prisma.AuditUncheckedUpdateManyInput>
  /**
   * Filter which Audits to update
   */
  where?: Prisma.AuditWhereInput
  /**
   * Limit how many Audits to update.
   */
  limit?: number
}

/**
 * Audit updateManyAndReturn
 */
export type AuditUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * The data used to update Audits.
   */
  data: Prisma.XOR<Prisma.AuditUpdateManyMutationInput, Prisma.AuditUncheckedUpdateManyInput>
  /**
   * Filter which Audits to update
   */
  where?: Prisma.AuditWhereInput
  /**
   * Limit how many Audits to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Audit upsert
 */
export type AuditUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditInclude<ExtArgs> | null
  /**
   * The filter to search for the Audit to update in case it exists.
   */
  where: Prisma.AuditWhereUniqueInput
  /**
   * In case the Audit found by the `where` argument doesn't exist, create a new Audit with this data.
   */
  create: Prisma.XOR<Prisma.AuditCreateInput, Prisma.AuditUncheckedCreateInput>
  /**
   * In case the Audit was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AuditUpdateInput, Prisma.AuditUncheckedUpdateInput>
}

/**
 * Audit delete
 */
export type AuditDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditInclude<ExtArgs> | null
  /**
   * Filter which Audit to delete.
   */
  where: Prisma.AuditWhereUniqueInput
}

/**
 * Audit deleteMany
 */
export type AuditDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Audits to delete
   */
  where?: Prisma.AuditWhereInput
  /**
   * Limit how many Audits to delete.
   */
  limit?: number
}

/**
 * Audit without action
 */
export type AuditDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Audit
   */
  select?: Prisma.AuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Audit
   */
  omit?: Prisma.AuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditInclude<ExtArgs> | null
}
