
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FamilyUnit` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FamilyUnit
 * 
 */
export type FamilyUnitModel = runtime.Types.Result.DefaultSelection<Prisma.$FamilyUnitPayload>

export type AggregateFamilyUnit = {
  _count: FamilyUnitCountAggregateOutputType | null
  _min: FamilyUnitMinAggregateOutputType | null
  _max: FamilyUnitMaxAggregateOutputType | null
}

export type FamilyUnitMinAggregateOutputType = {
  id: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type FamilyUnitMaxAggregateOutputType = {
  id: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type FamilyUnitCountAggregateOutputType = {
  id: number
  description: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type FamilyUnitMinAggregateInputType = {
  id?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type FamilyUnitMaxAggregateInputType = {
  id?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type FamilyUnitCountAggregateInputType = {
  id?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type FamilyUnitAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FamilyUnit to aggregate.
   */
  where?: Prisma.FamilyUnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FamilyUnits to fetch.
   */
  orderBy?: Prisma.FamilyUnitOrderByWithRelationInput | Prisma.FamilyUnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FamilyUnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FamilyUnits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FamilyUnits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FamilyUnits
  **/
  _count?: true | FamilyUnitCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FamilyUnitMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FamilyUnitMaxAggregateInputType
}

export type GetFamilyUnitAggregateType<T extends FamilyUnitAggregateArgs> = {
      [P in keyof T & keyof AggregateFamilyUnit]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFamilyUnit[P]>
    : Prisma.GetScalarType<T[P], AggregateFamilyUnit[P]>
}




export type FamilyUnitGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FamilyUnitWhereInput
  orderBy?: Prisma.FamilyUnitOrderByWithAggregationInput | Prisma.FamilyUnitOrderByWithAggregationInput[]
  by: Prisma.FamilyUnitScalarFieldEnum[] | Prisma.FamilyUnitScalarFieldEnum
  having?: Prisma.FamilyUnitScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FamilyUnitCountAggregateInputType | true
  _min?: FamilyUnitMinAggregateInputType
  _max?: FamilyUnitMaxAggregateInputType
}

export type FamilyUnitGroupByOutputType = {
  id: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: FamilyUnitCountAggregateOutputType | null
  _min: FamilyUnitMinAggregateOutputType | null
  _max: FamilyUnitMaxAggregateOutputType | null
}

export type GetFamilyUnitGroupByPayload<T extends FamilyUnitGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FamilyUnitGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FamilyUnitGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FamilyUnitGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FamilyUnitGroupByOutputType[P]>
      }
    >
  >



export type FamilyUnitWhereInput = {
  AND?: Prisma.FamilyUnitWhereInput | Prisma.FamilyUnitWhereInput[]
  OR?: Prisma.FamilyUnitWhereInput[]
  NOT?: Prisma.FamilyUnitWhereInput | Prisma.FamilyUnitWhereInput[]
  id?: Prisma.UuidFilter<"FamilyUnit"> | string
  description?: Prisma.StringNullableFilter<"FamilyUnit"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FamilyUnit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FamilyUnit"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"FamilyUnit"> | Date | string | null
  memberships?: Prisma.FamilyMembershipListRelationFilter
}

export type FamilyUnitOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  memberships?: Prisma.FamilyMembershipOrderByRelationAggregateInput
}

export type FamilyUnitWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FamilyUnitWhereInput | Prisma.FamilyUnitWhereInput[]
  OR?: Prisma.FamilyUnitWhereInput[]
  NOT?: Prisma.FamilyUnitWhereInput | Prisma.FamilyUnitWhereInput[]
  description?: Prisma.StringNullableFilter<"FamilyUnit"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FamilyUnit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FamilyUnit"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"FamilyUnit"> | Date | string | null
  memberships?: Prisma.FamilyMembershipListRelationFilter
}, "id">

export type FamilyUnitOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.FamilyUnitCountOrderByAggregateInput
  _max?: Prisma.FamilyUnitMaxOrderByAggregateInput
  _min?: Prisma.FamilyUnitMinOrderByAggregateInput
}

export type FamilyUnitScalarWhereWithAggregatesInput = {
  AND?: Prisma.FamilyUnitScalarWhereWithAggregatesInput | Prisma.FamilyUnitScalarWhereWithAggregatesInput[]
  OR?: Prisma.FamilyUnitScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FamilyUnitScalarWhereWithAggregatesInput | Prisma.FamilyUnitScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"FamilyUnit"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"FamilyUnit"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FamilyUnit"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FamilyUnit"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"FamilyUnit"> | Date | string | null
}

export type FamilyUnitCreateInput = {
  id?: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  memberships?: Prisma.FamilyMembershipCreateNestedManyWithoutFamilyUnitInput
}

export type FamilyUnitUncheckedCreateInput = {
  id?: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  memberships?: Prisma.FamilyMembershipUncheckedCreateNestedManyWithoutFamilyUnitInput
}

export type FamilyUnitUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  memberships?: Prisma.FamilyMembershipUpdateManyWithoutFamilyUnitNestedInput
}

export type FamilyUnitUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  memberships?: Prisma.FamilyMembershipUncheckedUpdateManyWithoutFamilyUnitNestedInput
}

export type FamilyUnitCreateManyInput = {
  id?: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type FamilyUnitUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FamilyUnitUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FamilyUnitCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type FamilyUnitMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type FamilyUnitMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type FamilyUnitScalarRelationFilter = {
  is?: Prisma.FamilyUnitWhereInput
  isNot?: Prisma.FamilyUnitWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type FamilyUnitCreateNestedOneWithoutMembershipsInput = {
  create?: Prisma.XOR<Prisma.FamilyUnitCreateWithoutMembershipsInput, Prisma.FamilyUnitUncheckedCreateWithoutMembershipsInput>
  connectOrCreate?: Prisma.FamilyUnitCreateOrConnectWithoutMembershipsInput
  connect?: Prisma.FamilyUnitWhereUniqueInput
}

export type FamilyUnitUpdateOneRequiredWithoutMembershipsNestedInput = {
  create?: Prisma.XOR<Prisma.FamilyUnitCreateWithoutMembershipsInput, Prisma.FamilyUnitUncheckedCreateWithoutMembershipsInput>
  connectOrCreate?: Prisma.FamilyUnitCreateOrConnectWithoutMembershipsInput
  upsert?: Prisma.FamilyUnitUpsertWithoutMembershipsInput
  connect?: Prisma.FamilyUnitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FamilyUnitUpdateToOneWithWhereWithoutMembershipsInput, Prisma.FamilyUnitUpdateWithoutMembershipsInput>, Prisma.FamilyUnitUncheckedUpdateWithoutMembershipsInput>
}

export type FamilyUnitCreateWithoutMembershipsInput = {
  id?: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type FamilyUnitUncheckedCreateWithoutMembershipsInput = {
  id?: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type FamilyUnitCreateOrConnectWithoutMembershipsInput = {
  where: Prisma.FamilyUnitWhereUniqueInput
  create: Prisma.XOR<Prisma.FamilyUnitCreateWithoutMembershipsInput, Prisma.FamilyUnitUncheckedCreateWithoutMembershipsInput>
}

export type FamilyUnitUpsertWithoutMembershipsInput = {
  update: Prisma.XOR<Prisma.FamilyUnitUpdateWithoutMembershipsInput, Prisma.FamilyUnitUncheckedUpdateWithoutMembershipsInput>
  create: Prisma.XOR<Prisma.FamilyUnitCreateWithoutMembershipsInput, Prisma.FamilyUnitUncheckedCreateWithoutMembershipsInput>
  where?: Prisma.FamilyUnitWhereInput
}

export type FamilyUnitUpdateToOneWithWhereWithoutMembershipsInput = {
  where?: Prisma.FamilyUnitWhereInput
  data: Prisma.XOR<Prisma.FamilyUnitUpdateWithoutMembershipsInput, Prisma.FamilyUnitUncheckedUpdateWithoutMembershipsInput>
}

export type FamilyUnitUpdateWithoutMembershipsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FamilyUnitUncheckedUpdateWithoutMembershipsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type FamilyUnitCountOutputType
 */

export type FamilyUnitCountOutputType = {
  memberships: number
}

export type FamilyUnitCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  memberships?: boolean | FamilyUnitCountOutputTypeCountMembershipsArgs
}

/**
 * FamilyUnitCountOutputType without action
 */
export type FamilyUnitCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnitCountOutputType
   */
  select?: Prisma.FamilyUnitCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FamilyUnitCountOutputType without action
 */
export type FamilyUnitCountOutputTypeCountMembershipsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FamilyMembershipWhereInput
}


export type FamilyUnitSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  memberships?: boolean | Prisma.FamilyUnit$membershipsArgs<ExtArgs>
  _count?: boolean | Prisma.FamilyUnitCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["familyUnit"]>

export type FamilyUnitSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["familyUnit"]>

export type FamilyUnitSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["familyUnit"]>

export type FamilyUnitSelectScalar = {
  id?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type FamilyUnitOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "description" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["familyUnit"]>
export type FamilyUnitInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  memberships?: boolean | Prisma.FamilyUnit$membershipsArgs<ExtArgs>
  _count?: boolean | Prisma.FamilyUnitCountOutputTypeDefaultArgs<ExtArgs>
}
export type FamilyUnitIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type FamilyUnitIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $FamilyUnitPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FamilyUnit"
  objects: {
    memberships: Prisma.$FamilyMembershipPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    description: string | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["familyUnit"]>
  composites: {}
}

export type FamilyUnitGetPayload<S extends boolean | null | undefined | FamilyUnitDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload, S>

export type FamilyUnitCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FamilyUnitFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FamilyUnitCountAggregateInputType | true
  }

export interface FamilyUnitDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FamilyUnit'], meta: { name: 'FamilyUnit' } }
  /**
   * Find zero or one FamilyUnit that matches the filter.
   * @param {FamilyUnitFindUniqueArgs} args - Arguments to find a FamilyUnit
   * @example
   * // Get one FamilyUnit
   * const familyUnit = await prisma.familyUnit.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FamilyUnitFindUniqueArgs>(args: Prisma.SelectSubset<T, FamilyUnitFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FamilyUnitClient<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FamilyUnit that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FamilyUnitFindUniqueOrThrowArgs} args - Arguments to find a FamilyUnit
   * @example
   * // Get one FamilyUnit
   * const familyUnit = await prisma.familyUnit.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FamilyUnitFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FamilyUnitFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FamilyUnitClient<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FamilyUnit that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyUnitFindFirstArgs} args - Arguments to find a FamilyUnit
   * @example
   * // Get one FamilyUnit
   * const familyUnit = await prisma.familyUnit.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FamilyUnitFindFirstArgs>(args?: Prisma.SelectSubset<T, FamilyUnitFindFirstArgs<ExtArgs>>): Prisma.Prisma__FamilyUnitClient<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FamilyUnit that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyUnitFindFirstOrThrowArgs} args - Arguments to find a FamilyUnit
   * @example
   * // Get one FamilyUnit
   * const familyUnit = await prisma.familyUnit.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FamilyUnitFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FamilyUnitFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FamilyUnitClient<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FamilyUnits that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyUnitFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FamilyUnits
   * const familyUnits = await prisma.familyUnit.findMany()
   * 
   * // Get first 10 FamilyUnits
   * const familyUnits = await prisma.familyUnit.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const familyUnitWithIdOnly = await prisma.familyUnit.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FamilyUnitFindManyArgs>(args?: Prisma.SelectSubset<T, FamilyUnitFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FamilyUnit.
   * @param {FamilyUnitCreateArgs} args - Arguments to create a FamilyUnit.
   * @example
   * // Create one FamilyUnit
   * const FamilyUnit = await prisma.familyUnit.create({
   *   data: {
   *     // ... data to create a FamilyUnit
   *   }
   * })
   * 
   */
  create<T extends FamilyUnitCreateArgs>(args: Prisma.SelectSubset<T, FamilyUnitCreateArgs<ExtArgs>>): Prisma.Prisma__FamilyUnitClient<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FamilyUnits.
   * @param {FamilyUnitCreateManyArgs} args - Arguments to create many FamilyUnits.
   * @example
   * // Create many FamilyUnits
   * const familyUnit = await prisma.familyUnit.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FamilyUnitCreateManyArgs>(args?: Prisma.SelectSubset<T, FamilyUnitCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FamilyUnits and returns the data saved in the database.
   * @param {FamilyUnitCreateManyAndReturnArgs} args - Arguments to create many FamilyUnits.
   * @example
   * // Create many FamilyUnits
   * const familyUnit = await prisma.familyUnit.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FamilyUnits and only return the `id`
   * const familyUnitWithIdOnly = await prisma.familyUnit.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FamilyUnitCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FamilyUnitCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FamilyUnit.
   * @param {FamilyUnitDeleteArgs} args - Arguments to delete one FamilyUnit.
   * @example
   * // Delete one FamilyUnit
   * const FamilyUnit = await prisma.familyUnit.delete({
   *   where: {
   *     // ... filter to delete one FamilyUnit
   *   }
   * })
   * 
   */
  delete<T extends FamilyUnitDeleteArgs>(args: Prisma.SelectSubset<T, FamilyUnitDeleteArgs<ExtArgs>>): Prisma.Prisma__FamilyUnitClient<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FamilyUnit.
   * @param {FamilyUnitUpdateArgs} args - Arguments to update one FamilyUnit.
   * @example
   * // Update one FamilyUnit
   * const familyUnit = await prisma.familyUnit.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FamilyUnitUpdateArgs>(args: Prisma.SelectSubset<T, FamilyUnitUpdateArgs<ExtArgs>>): Prisma.Prisma__FamilyUnitClient<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FamilyUnits.
   * @param {FamilyUnitDeleteManyArgs} args - Arguments to filter FamilyUnits to delete.
   * @example
   * // Delete a few FamilyUnits
   * const { count } = await prisma.familyUnit.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FamilyUnitDeleteManyArgs>(args?: Prisma.SelectSubset<T, FamilyUnitDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FamilyUnits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyUnitUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FamilyUnits
   * const familyUnit = await prisma.familyUnit.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FamilyUnitUpdateManyArgs>(args: Prisma.SelectSubset<T, FamilyUnitUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FamilyUnits and returns the data updated in the database.
   * @param {FamilyUnitUpdateManyAndReturnArgs} args - Arguments to update many FamilyUnits.
   * @example
   * // Update many FamilyUnits
   * const familyUnit = await prisma.familyUnit.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FamilyUnits and only return the `id`
   * const familyUnitWithIdOnly = await prisma.familyUnit.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FamilyUnitUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FamilyUnitUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FamilyUnit.
   * @param {FamilyUnitUpsertArgs} args - Arguments to update or create a FamilyUnit.
   * @example
   * // Update or create a FamilyUnit
   * const familyUnit = await prisma.familyUnit.upsert({
   *   create: {
   *     // ... data to create a FamilyUnit
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FamilyUnit we want to update
   *   }
   * })
   */
  upsert<T extends FamilyUnitUpsertArgs>(args: Prisma.SelectSubset<T, FamilyUnitUpsertArgs<ExtArgs>>): Prisma.Prisma__FamilyUnitClient<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FamilyUnits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyUnitCountArgs} args - Arguments to filter FamilyUnits to count.
   * @example
   * // Count the number of FamilyUnits
   * const count = await prisma.familyUnit.count({
   *   where: {
   *     // ... the filter for the FamilyUnits we want to count
   *   }
   * })
  **/
  count<T extends FamilyUnitCountArgs>(
    args?: Prisma.Subset<T, FamilyUnitCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FamilyUnitCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FamilyUnit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyUnitAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FamilyUnitAggregateArgs>(args: Prisma.Subset<T, FamilyUnitAggregateArgs>): Prisma.PrismaPromise<GetFamilyUnitAggregateType<T>>

  /**
   * Group by FamilyUnit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyUnitGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FamilyUnitGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FamilyUnitGroupByArgs['orderBy'] }
      : { orderBy?: FamilyUnitGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FamilyUnitGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFamilyUnitGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FamilyUnit model
 */
readonly fields: FamilyUnitFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FamilyUnit.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FamilyUnitClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  memberships<T extends Prisma.FamilyUnit$membershipsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FamilyUnit$membershipsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FamilyUnit model
 */
export interface FamilyUnitFieldRefs {
  readonly id: Prisma.FieldRef<"FamilyUnit", 'String'>
  readonly description: Prisma.FieldRef<"FamilyUnit", 'String'>
  readonly createdAt: Prisma.FieldRef<"FamilyUnit", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FamilyUnit", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"FamilyUnit", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FamilyUnit findUnique
 */
export type FamilyUnitFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyUnitInclude<ExtArgs> | null
  /**
   * Filter, which FamilyUnit to fetch.
   */
  where: Prisma.FamilyUnitWhereUniqueInput
}

/**
 * FamilyUnit findUniqueOrThrow
 */
export type FamilyUnitFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyUnitInclude<ExtArgs> | null
  /**
   * Filter, which FamilyUnit to fetch.
   */
  where: Prisma.FamilyUnitWhereUniqueInput
}

/**
 * FamilyUnit findFirst
 */
export type FamilyUnitFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyUnitInclude<ExtArgs> | null
  /**
   * Filter, which FamilyUnit to fetch.
   */
  where?: Prisma.FamilyUnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FamilyUnits to fetch.
   */
  orderBy?: Prisma.FamilyUnitOrderByWithRelationInput | Prisma.FamilyUnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FamilyUnits.
   */
  cursor?: Prisma.FamilyUnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FamilyUnits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FamilyUnits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FamilyUnits.
   */
  distinct?: Prisma.FamilyUnitScalarFieldEnum | Prisma.FamilyUnitScalarFieldEnum[]
}

/**
 * FamilyUnit findFirstOrThrow
 */
export type FamilyUnitFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyUnitInclude<ExtArgs> | null
  /**
   * Filter, which FamilyUnit to fetch.
   */
  where?: Prisma.FamilyUnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FamilyUnits to fetch.
   */
  orderBy?: Prisma.FamilyUnitOrderByWithRelationInput | Prisma.FamilyUnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FamilyUnits.
   */
  cursor?: Prisma.FamilyUnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FamilyUnits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FamilyUnits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FamilyUnits.
   */
  distinct?: Prisma.FamilyUnitScalarFieldEnum | Prisma.FamilyUnitScalarFieldEnum[]
}

/**
 * FamilyUnit findMany
 */
export type FamilyUnitFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyUnitInclude<ExtArgs> | null
  /**
   * Filter, which FamilyUnits to fetch.
   */
  where?: Prisma.FamilyUnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FamilyUnits to fetch.
   */
  orderBy?: Prisma.FamilyUnitOrderByWithRelationInput | Prisma.FamilyUnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FamilyUnits.
   */
  cursor?: Prisma.FamilyUnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FamilyUnits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FamilyUnits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FamilyUnits.
   */
  distinct?: Prisma.FamilyUnitScalarFieldEnum | Prisma.FamilyUnitScalarFieldEnum[]
}

/**
 * FamilyUnit create
 */
export type FamilyUnitCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyUnitInclude<ExtArgs> | null
  /**
   * The data needed to create a FamilyUnit.
   */
  data: Prisma.XOR<Prisma.FamilyUnitCreateInput, Prisma.FamilyUnitUncheckedCreateInput>
}

/**
 * FamilyUnit createMany
 */
export type FamilyUnitCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FamilyUnits.
   */
  data: Prisma.FamilyUnitCreateManyInput | Prisma.FamilyUnitCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FamilyUnit createManyAndReturn
 */
export type FamilyUnitCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * The data used to create many FamilyUnits.
   */
  data: Prisma.FamilyUnitCreateManyInput | Prisma.FamilyUnitCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FamilyUnit update
 */
export type FamilyUnitUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyUnitInclude<ExtArgs> | null
  /**
   * The data needed to update a FamilyUnit.
   */
  data: Prisma.XOR<Prisma.FamilyUnitUpdateInput, Prisma.FamilyUnitUncheckedUpdateInput>
  /**
   * Choose, which FamilyUnit to update.
   */
  where: Prisma.FamilyUnitWhereUniqueInput
}

/**
 * FamilyUnit updateMany
 */
export type FamilyUnitUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FamilyUnits.
   */
  data: Prisma.XOR<Prisma.FamilyUnitUpdateManyMutationInput, Prisma.FamilyUnitUncheckedUpdateManyInput>
  /**
   * Filter which FamilyUnits to update
   */
  where?: Prisma.FamilyUnitWhereInput
  /**
   * Limit how many FamilyUnits to update.
   */
  limit?: number
}

/**
 * FamilyUnit updateManyAndReturn
 */
export type FamilyUnitUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * The data used to update FamilyUnits.
   */
  data: Prisma.XOR<Prisma.FamilyUnitUpdateManyMutationInput, Prisma.FamilyUnitUncheckedUpdateManyInput>
  /**
   * Filter which FamilyUnits to update
   */
  where?: Prisma.FamilyUnitWhereInput
  /**
   * Limit how many FamilyUnits to update.
   */
  limit?: number
}

/**
 * FamilyUnit upsert
 */
export type FamilyUnitUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyUnitInclude<ExtArgs> | null
  /**
   * The filter to search for the FamilyUnit to update in case it exists.
   */
  where: Prisma.FamilyUnitWhereUniqueInput
  /**
   * In case the FamilyUnit found by the `where` argument doesn't exist, create a new FamilyUnit with this data.
   */
  create: Prisma.XOR<Prisma.FamilyUnitCreateInput, Prisma.FamilyUnitUncheckedCreateInput>
  /**
   * In case the FamilyUnit was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FamilyUnitUpdateInput, Prisma.FamilyUnitUncheckedUpdateInput>
}

/**
 * FamilyUnit delete
 */
export type FamilyUnitDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyUnitInclude<ExtArgs> | null
  /**
   * Filter which FamilyUnit to delete.
   */
  where: Prisma.FamilyUnitWhereUniqueInput
}

/**
 * FamilyUnit deleteMany
 */
export type FamilyUnitDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FamilyUnits to delete
   */
  where?: Prisma.FamilyUnitWhereInput
  /**
   * Limit how many FamilyUnits to delete.
   */
  limit?: number
}

/**
 * FamilyUnit.memberships
 */
export type FamilyUnit$membershipsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
  where?: Prisma.FamilyMembershipWhereInput
  orderBy?: Prisma.FamilyMembershipOrderByWithRelationInput | Prisma.FamilyMembershipOrderByWithRelationInput[]
  cursor?: Prisma.FamilyMembershipWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FamilyMembershipScalarFieldEnum | Prisma.FamilyMembershipScalarFieldEnum[]
}

/**
 * FamilyUnit without action
 */
export type FamilyUnitDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyUnit
   */
  select?: Prisma.FamilyUnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyUnit
   */
  omit?: Prisma.FamilyUnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyUnitInclude<ExtArgs> | null
}
