
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FamilyMembership` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FamilyMembership
 * 
 */
export type FamilyMembershipModel = runtime.Types.Result.DefaultSelection<Prisma.$FamilyMembershipPayload>

export type AggregateFamilyMembership = {
  _count: FamilyMembershipCountAggregateOutputType | null
  _min: FamilyMembershipMinAggregateOutputType | null
  _max: FamilyMembershipMaxAggregateOutputType | null
}

export type FamilyMembershipMinAggregateOutputType = {
  id: string | null
  personId: string | null
  familyUnitId: string | null
  role: $Enums.FamilyRole | null
}

export type FamilyMembershipMaxAggregateOutputType = {
  id: string | null
  personId: string | null
  familyUnitId: string | null
  role: $Enums.FamilyRole | null
}

export type FamilyMembershipCountAggregateOutputType = {
  id: number
  personId: number
  familyUnitId: number
  role: number
  _all: number
}


export type FamilyMembershipMinAggregateInputType = {
  id?: true
  personId?: true
  familyUnitId?: true
  role?: true
}

export type FamilyMembershipMaxAggregateInputType = {
  id?: true
  personId?: true
  familyUnitId?: true
  role?: true
}

export type FamilyMembershipCountAggregateInputType = {
  id?: true
  personId?: true
  familyUnitId?: true
  role?: true
  _all?: true
}

export type FamilyMembershipAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FamilyMembership to aggregate.
   */
  where?: Prisma.FamilyMembershipWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FamilyMemberships to fetch.
   */
  orderBy?: Prisma.FamilyMembershipOrderByWithRelationInput | Prisma.FamilyMembershipOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FamilyMembershipWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FamilyMemberships from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FamilyMemberships.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FamilyMemberships
  **/
  _count?: true | FamilyMembershipCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FamilyMembershipMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FamilyMembershipMaxAggregateInputType
}

export type GetFamilyMembershipAggregateType<T extends FamilyMembershipAggregateArgs> = {
      [P in keyof T & keyof AggregateFamilyMembership]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFamilyMembership[P]>
    : Prisma.GetScalarType<T[P], AggregateFamilyMembership[P]>
}




export type FamilyMembershipGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FamilyMembershipWhereInput
  orderBy?: Prisma.FamilyMembershipOrderByWithAggregationInput | Prisma.FamilyMembershipOrderByWithAggregationInput[]
  by: Prisma.FamilyMembershipScalarFieldEnum[] | Prisma.FamilyMembershipScalarFieldEnum
  having?: Prisma.FamilyMembershipScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FamilyMembershipCountAggregateInputType | true
  _min?: FamilyMembershipMinAggregateInputType
  _max?: FamilyMembershipMaxAggregateInputType
}

export type FamilyMembershipGroupByOutputType = {
  id: string
  personId: string
  familyUnitId: string
  role: $Enums.FamilyRole
  _count: FamilyMembershipCountAggregateOutputType | null
  _min: FamilyMembershipMinAggregateOutputType | null
  _max: FamilyMembershipMaxAggregateOutputType | null
}

export type GetFamilyMembershipGroupByPayload<T extends FamilyMembershipGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FamilyMembershipGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FamilyMembershipGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FamilyMembershipGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FamilyMembershipGroupByOutputType[P]>
      }
    >
  >



export type FamilyMembershipWhereInput = {
  AND?: Prisma.FamilyMembershipWhereInput | Prisma.FamilyMembershipWhereInput[]
  OR?: Prisma.FamilyMembershipWhereInput[]
  NOT?: Prisma.FamilyMembershipWhereInput | Prisma.FamilyMembershipWhereInput[]
  id?: Prisma.UuidFilter<"FamilyMembership"> | string
  personId?: Prisma.UuidFilter<"FamilyMembership"> | string
  familyUnitId?: Prisma.UuidFilter<"FamilyMembership"> | string
  role?: Prisma.EnumFamilyRoleFilter<"FamilyMembership"> | $Enums.FamilyRole
  person?: Prisma.XOR<Prisma.PersonScalarRelationFilter, Prisma.PersonWhereInput>
  familyUnit?: Prisma.XOR<Prisma.FamilyUnitScalarRelationFilter, Prisma.FamilyUnitWhereInput>
}

export type FamilyMembershipOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  personId?: Prisma.SortOrder
  familyUnitId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  person?: Prisma.PersonOrderByWithRelationInput
  familyUnit?: Prisma.FamilyUnitOrderByWithRelationInput
}

export type FamilyMembershipWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FamilyMembershipWhereInput | Prisma.FamilyMembershipWhereInput[]
  OR?: Prisma.FamilyMembershipWhereInput[]
  NOT?: Prisma.FamilyMembershipWhereInput | Prisma.FamilyMembershipWhereInput[]
  personId?: Prisma.UuidFilter<"FamilyMembership"> | string
  familyUnitId?: Prisma.UuidFilter<"FamilyMembership"> | string
  role?: Prisma.EnumFamilyRoleFilter<"FamilyMembership"> | $Enums.FamilyRole
  person?: Prisma.XOR<Prisma.PersonScalarRelationFilter, Prisma.PersonWhereInput>
  familyUnit?: Prisma.XOR<Prisma.FamilyUnitScalarRelationFilter, Prisma.FamilyUnitWhereInput>
}, "id">

export type FamilyMembershipOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  personId?: Prisma.SortOrder
  familyUnitId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  _count?: Prisma.FamilyMembershipCountOrderByAggregateInput
  _max?: Prisma.FamilyMembershipMaxOrderByAggregateInput
  _min?: Prisma.FamilyMembershipMinOrderByAggregateInput
}

export type FamilyMembershipScalarWhereWithAggregatesInput = {
  AND?: Prisma.FamilyMembershipScalarWhereWithAggregatesInput | Prisma.FamilyMembershipScalarWhereWithAggregatesInput[]
  OR?: Prisma.FamilyMembershipScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FamilyMembershipScalarWhereWithAggregatesInput | Prisma.FamilyMembershipScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"FamilyMembership"> | string
  personId?: Prisma.UuidWithAggregatesFilter<"FamilyMembership"> | string
  familyUnitId?: Prisma.UuidWithAggregatesFilter<"FamilyMembership"> | string
  role?: Prisma.EnumFamilyRoleWithAggregatesFilter<"FamilyMembership"> | $Enums.FamilyRole
}

export type FamilyMembershipCreateInput = {
  id?: string
  role: $Enums.FamilyRole
  person: Prisma.PersonCreateNestedOneWithoutMembershipsInput
  familyUnit: Prisma.FamilyUnitCreateNestedOneWithoutMembershipsInput
}

export type FamilyMembershipUncheckedCreateInput = {
  id?: string
  personId: string
  familyUnitId: string
  role: $Enums.FamilyRole
}

export type FamilyMembershipUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumFamilyRoleFieldUpdateOperationsInput | $Enums.FamilyRole
  person?: Prisma.PersonUpdateOneRequiredWithoutMembershipsNestedInput
  familyUnit?: Prisma.FamilyUnitUpdateOneRequiredWithoutMembershipsNestedInput
}

export type FamilyMembershipUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  personId?: Prisma.StringFieldUpdateOperationsInput | string
  familyUnitId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumFamilyRoleFieldUpdateOperationsInput | $Enums.FamilyRole
}

export type FamilyMembershipCreateManyInput = {
  id?: string
  personId: string
  familyUnitId: string
  role: $Enums.FamilyRole
}

export type FamilyMembershipUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumFamilyRoleFieldUpdateOperationsInput | $Enums.FamilyRole
}

export type FamilyMembershipUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  personId?: Prisma.StringFieldUpdateOperationsInput | string
  familyUnitId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumFamilyRoleFieldUpdateOperationsInput | $Enums.FamilyRole
}

export type FamilyMembershipListRelationFilter = {
  every?: Prisma.FamilyMembershipWhereInput
  some?: Prisma.FamilyMembershipWhereInput
  none?: Prisma.FamilyMembershipWhereInput
}

export type FamilyMembershipOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FamilyMembershipCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  personId?: Prisma.SortOrder
  familyUnitId?: Prisma.SortOrder
  role?: Prisma.SortOrder
}

export type FamilyMembershipMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  personId?: Prisma.SortOrder
  familyUnitId?: Prisma.SortOrder
  role?: Prisma.SortOrder
}

export type FamilyMembershipMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  personId?: Prisma.SortOrder
  familyUnitId?: Prisma.SortOrder
  role?: Prisma.SortOrder
}

export type FamilyMembershipCreateNestedManyWithoutFamilyUnitInput = {
  create?: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutFamilyUnitInput, Prisma.FamilyMembershipUncheckedCreateWithoutFamilyUnitInput> | Prisma.FamilyMembershipCreateWithoutFamilyUnitInput[] | Prisma.FamilyMembershipUncheckedCreateWithoutFamilyUnitInput[]
  connectOrCreate?: Prisma.FamilyMembershipCreateOrConnectWithoutFamilyUnitInput | Prisma.FamilyMembershipCreateOrConnectWithoutFamilyUnitInput[]
  createMany?: Prisma.FamilyMembershipCreateManyFamilyUnitInputEnvelope
  connect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
}

export type FamilyMembershipUncheckedCreateNestedManyWithoutFamilyUnitInput = {
  create?: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutFamilyUnitInput, Prisma.FamilyMembershipUncheckedCreateWithoutFamilyUnitInput> | Prisma.FamilyMembershipCreateWithoutFamilyUnitInput[] | Prisma.FamilyMembershipUncheckedCreateWithoutFamilyUnitInput[]
  connectOrCreate?: Prisma.FamilyMembershipCreateOrConnectWithoutFamilyUnitInput | Prisma.FamilyMembershipCreateOrConnectWithoutFamilyUnitInput[]
  createMany?: Prisma.FamilyMembershipCreateManyFamilyUnitInputEnvelope
  connect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
}

export type FamilyMembershipUpdateManyWithoutFamilyUnitNestedInput = {
  create?: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutFamilyUnitInput, Prisma.FamilyMembershipUncheckedCreateWithoutFamilyUnitInput> | Prisma.FamilyMembershipCreateWithoutFamilyUnitInput[] | Prisma.FamilyMembershipUncheckedCreateWithoutFamilyUnitInput[]
  connectOrCreate?: Prisma.FamilyMembershipCreateOrConnectWithoutFamilyUnitInput | Prisma.FamilyMembershipCreateOrConnectWithoutFamilyUnitInput[]
  upsert?: Prisma.FamilyMembershipUpsertWithWhereUniqueWithoutFamilyUnitInput | Prisma.FamilyMembershipUpsertWithWhereUniqueWithoutFamilyUnitInput[]
  createMany?: Prisma.FamilyMembershipCreateManyFamilyUnitInputEnvelope
  set?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  disconnect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  delete?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  connect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  update?: Prisma.FamilyMembershipUpdateWithWhereUniqueWithoutFamilyUnitInput | Prisma.FamilyMembershipUpdateWithWhereUniqueWithoutFamilyUnitInput[]
  updateMany?: Prisma.FamilyMembershipUpdateManyWithWhereWithoutFamilyUnitInput | Prisma.FamilyMembershipUpdateManyWithWhereWithoutFamilyUnitInput[]
  deleteMany?: Prisma.FamilyMembershipScalarWhereInput | Prisma.FamilyMembershipScalarWhereInput[]
}

export type FamilyMembershipUncheckedUpdateManyWithoutFamilyUnitNestedInput = {
  create?: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutFamilyUnitInput, Prisma.FamilyMembershipUncheckedCreateWithoutFamilyUnitInput> | Prisma.FamilyMembershipCreateWithoutFamilyUnitInput[] | Prisma.FamilyMembershipUncheckedCreateWithoutFamilyUnitInput[]
  connectOrCreate?: Prisma.FamilyMembershipCreateOrConnectWithoutFamilyUnitInput | Prisma.FamilyMembershipCreateOrConnectWithoutFamilyUnitInput[]
  upsert?: Prisma.FamilyMembershipUpsertWithWhereUniqueWithoutFamilyUnitInput | Prisma.FamilyMembershipUpsertWithWhereUniqueWithoutFamilyUnitInput[]
  createMany?: Prisma.FamilyMembershipCreateManyFamilyUnitInputEnvelope
  set?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  disconnect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  delete?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  connect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  update?: Prisma.FamilyMembershipUpdateWithWhereUniqueWithoutFamilyUnitInput | Prisma.FamilyMembershipUpdateWithWhereUniqueWithoutFamilyUnitInput[]
  updateMany?: Prisma.FamilyMembershipUpdateManyWithWhereWithoutFamilyUnitInput | Prisma.FamilyMembershipUpdateManyWithWhereWithoutFamilyUnitInput[]
  deleteMany?: Prisma.FamilyMembershipScalarWhereInput | Prisma.FamilyMembershipScalarWhereInput[]
}

export type EnumFamilyRoleFieldUpdateOperationsInput = {
  set?: $Enums.FamilyRole
}

export type FamilyMembershipCreateNestedManyWithoutPersonInput = {
  create?: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutPersonInput, Prisma.FamilyMembershipUncheckedCreateWithoutPersonInput> | Prisma.FamilyMembershipCreateWithoutPersonInput[] | Prisma.FamilyMembershipUncheckedCreateWithoutPersonInput[]
  connectOrCreate?: Prisma.FamilyMembershipCreateOrConnectWithoutPersonInput | Prisma.FamilyMembershipCreateOrConnectWithoutPersonInput[]
  createMany?: Prisma.FamilyMembershipCreateManyPersonInputEnvelope
  connect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
}

export type FamilyMembershipUncheckedCreateNestedManyWithoutPersonInput = {
  create?: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutPersonInput, Prisma.FamilyMembershipUncheckedCreateWithoutPersonInput> | Prisma.FamilyMembershipCreateWithoutPersonInput[] | Prisma.FamilyMembershipUncheckedCreateWithoutPersonInput[]
  connectOrCreate?: Prisma.FamilyMembershipCreateOrConnectWithoutPersonInput | Prisma.FamilyMembershipCreateOrConnectWithoutPersonInput[]
  createMany?: Prisma.FamilyMembershipCreateManyPersonInputEnvelope
  connect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
}

export type FamilyMembershipUpdateManyWithoutPersonNestedInput = {
  create?: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutPersonInput, Prisma.FamilyMembershipUncheckedCreateWithoutPersonInput> | Prisma.FamilyMembershipCreateWithoutPersonInput[] | Prisma.FamilyMembershipUncheckedCreateWithoutPersonInput[]
  connectOrCreate?: Prisma.FamilyMembershipCreateOrConnectWithoutPersonInput | Prisma.FamilyMembershipCreateOrConnectWithoutPersonInput[]
  upsert?: Prisma.FamilyMembershipUpsertWithWhereUniqueWithoutPersonInput | Prisma.FamilyMembershipUpsertWithWhereUniqueWithoutPersonInput[]
  createMany?: Prisma.FamilyMembershipCreateManyPersonInputEnvelope
  set?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  disconnect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  delete?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  connect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  update?: Prisma.FamilyMembershipUpdateWithWhereUniqueWithoutPersonInput | Prisma.FamilyMembershipUpdateWithWhereUniqueWithoutPersonInput[]
  updateMany?: Prisma.FamilyMembershipUpdateManyWithWhereWithoutPersonInput | Prisma.FamilyMembershipUpdateManyWithWhereWithoutPersonInput[]
  deleteMany?: Prisma.FamilyMembershipScalarWhereInput | Prisma.FamilyMembershipScalarWhereInput[]
}

export type FamilyMembershipUncheckedUpdateManyWithoutPersonNestedInput = {
  create?: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutPersonInput, Prisma.FamilyMembershipUncheckedCreateWithoutPersonInput> | Prisma.FamilyMembershipCreateWithoutPersonInput[] | Prisma.FamilyMembershipUncheckedCreateWithoutPersonInput[]
  connectOrCreate?: Prisma.FamilyMembershipCreateOrConnectWithoutPersonInput | Prisma.FamilyMembershipCreateOrConnectWithoutPersonInput[]
  upsert?: Prisma.FamilyMembershipUpsertWithWhereUniqueWithoutPersonInput | Prisma.FamilyMembershipUpsertWithWhereUniqueWithoutPersonInput[]
  createMany?: Prisma.FamilyMembershipCreateManyPersonInputEnvelope
  set?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  disconnect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  delete?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  connect?: Prisma.FamilyMembershipWhereUniqueInput | Prisma.FamilyMembershipWhereUniqueInput[]
  update?: Prisma.FamilyMembershipUpdateWithWhereUniqueWithoutPersonInput | Prisma.FamilyMembershipUpdateWithWhereUniqueWithoutPersonInput[]
  updateMany?: Prisma.FamilyMembershipUpdateManyWithWhereWithoutPersonInput | Prisma.FamilyMembershipUpdateManyWithWhereWithoutPersonInput[]
  deleteMany?: Prisma.FamilyMembershipScalarWhereInput | Prisma.FamilyMembershipScalarWhereInput[]
}

export type FamilyMembershipCreateWithoutFamilyUnitInput = {
  id?: string
  role: $Enums.FamilyRole
  person: Prisma.PersonCreateNestedOneWithoutMembershipsInput
}

export type FamilyMembershipUncheckedCreateWithoutFamilyUnitInput = {
  id?: string
  personId: string
  role: $Enums.FamilyRole
}

export type FamilyMembershipCreateOrConnectWithoutFamilyUnitInput = {
  where: Prisma.FamilyMembershipWhereUniqueInput
  create: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutFamilyUnitInput, Prisma.FamilyMembershipUncheckedCreateWithoutFamilyUnitInput>
}

export type FamilyMembershipCreateManyFamilyUnitInputEnvelope = {
  data: Prisma.FamilyMembershipCreateManyFamilyUnitInput | Prisma.FamilyMembershipCreateManyFamilyUnitInput[]
  skipDuplicates?: boolean
}

export type FamilyMembershipUpsertWithWhereUniqueWithoutFamilyUnitInput = {
  where: Prisma.FamilyMembershipWhereUniqueInput
  update: Prisma.XOR<Prisma.FamilyMembershipUpdateWithoutFamilyUnitInput, Prisma.FamilyMembershipUncheckedUpdateWithoutFamilyUnitInput>
  create: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutFamilyUnitInput, Prisma.FamilyMembershipUncheckedCreateWithoutFamilyUnitInput>
}

export type FamilyMembershipUpdateWithWhereUniqueWithoutFamilyUnitInput = {
  where: Prisma.FamilyMembershipWhereUniqueInput
  data: Prisma.XOR<Prisma.FamilyMembershipUpdateWithoutFamilyUnitInput, Prisma.FamilyMembershipUncheckedUpdateWithoutFamilyUnitInput>
}

export type FamilyMembershipUpdateManyWithWhereWithoutFamilyUnitInput = {
  where: Prisma.FamilyMembershipScalarWhereInput
  data: Prisma.XOR<Prisma.FamilyMembershipUpdateManyMutationInput, Prisma.FamilyMembershipUncheckedUpdateManyWithoutFamilyUnitInput>
}

export type FamilyMembershipScalarWhereInput = {
  AND?: Prisma.FamilyMembershipScalarWhereInput | Prisma.FamilyMembershipScalarWhereInput[]
  OR?: Prisma.FamilyMembershipScalarWhereInput[]
  NOT?: Prisma.FamilyMembershipScalarWhereInput | Prisma.FamilyMembershipScalarWhereInput[]
  id?: Prisma.UuidFilter<"FamilyMembership"> | string
  personId?: Prisma.UuidFilter<"FamilyMembership"> | string
  familyUnitId?: Prisma.UuidFilter<"FamilyMembership"> | string
  role?: Prisma.EnumFamilyRoleFilter<"FamilyMembership"> | $Enums.FamilyRole
}

export type FamilyMembershipCreateWithoutPersonInput = {
  id?: string
  role: $Enums.FamilyRole
  familyUnit: Prisma.FamilyUnitCreateNestedOneWithoutMembershipsInput
}

export type FamilyMembershipUncheckedCreateWithoutPersonInput = {
  id?: string
  familyUnitId: string
  role: $Enums.FamilyRole
}

export type FamilyMembershipCreateOrConnectWithoutPersonInput = {
  where: Prisma.FamilyMembershipWhereUniqueInput
  create: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutPersonInput, Prisma.FamilyMembershipUncheckedCreateWithoutPersonInput>
}

export type FamilyMembershipCreateManyPersonInputEnvelope = {
  data: Prisma.FamilyMembershipCreateManyPersonInput | Prisma.FamilyMembershipCreateManyPersonInput[]
  skipDuplicates?: boolean
}

export type FamilyMembershipUpsertWithWhereUniqueWithoutPersonInput = {
  where: Prisma.FamilyMembershipWhereUniqueInput
  update: Prisma.XOR<Prisma.FamilyMembershipUpdateWithoutPersonInput, Prisma.FamilyMembershipUncheckedUpdateWithoutPersonInput>
  create: Prisma.XOR<Prisma.FamilyMembershipCreateWithoutPersonInput, Prisma.FamilyMembershipUncheckedCreateWithoutPersonInput>
}

export type FamilyMembershipUpdateWithWhereUniqueWithoutPersonInput = {
  where: Prisma.FamilyMembershipWhereUniqueInput
  data: Prisma.XOR<Prisma.FamilyMembershipUpdateWithoutPersonInput, Prisma.FamilyMembershipUncheckedUpdateWithoutPersonInput>
}

export type FamilyMembershipUpdateManyWithWhereWithoutPersonInput = {
  where: Prisma.FamilyMembershipScalarWhereInput
  data: Prisma.XOR<Prisma.FamilyMembershipUpdateManyMutationInput, Prisma.FamilyMembershipUncheckedUpdateManyWithoutPersonInput>
}

export type FamilyMembershipCreateManyFamilyUnitInput = {
  id?: string
  personId: string
  role: $Enums.FamilyRole
}

export type FamilyMembershipUpdateWithoutFamilyUnitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumFamilyRoleFieldUpdateOperationsInput | $Enums.FamilyRole
  person?: Prisma.PersonUpdateOneRequiredWithoutMembershipsNestedInput
}

export type FamilyMembershipUncheckedUpdateWithoutFamilyUnitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  personId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumFamilyRoleFieldUpdateOperationsInput | $Enums.FamilyRole
}

export type FamilyMembershipUncheckedUpdateManyWithoutFamilyUnitInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  personId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumFamilyRoleFieldUpdateOperationsInput | $Enums.FamilyRole
}

export type FamilyMembershipCreateManyPersonInput = {
  id?: string
  familyUnitId: string
  role: $Enums.FamilyRole
}

export type FamilyMembershipUpdateWithoutPersonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumFamilyRoleFieldUpdateOperationsInput | $Enums.FamilyRole
  familyUnit?: Prisma.FamilyUnitUpdateOneRequiredWithoutMembershipsNestedInput
}

export type FamilyMembershipUncheckedUpdateWithoutPersonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  familyUnitId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumFamilyRoleFieldUpdateOperationsInput | $Enums.FamilyRole
}

export type FamilyMembershipUncheckedUpdateManyWithoutPersonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  familyUnitId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumFamilyRoleFieldUpdateOperationsInput | $Enums.FamilyRole
}



export type FamilyMembershipSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  personId?: boolean
  familyUnitId?: boolean
  role?: boolean
  person?: boolean | Prisma.PersonDefaultArgs<ExtArgs>
  familyUnit?: boolean | Prisma.FamilyUnitDefaultArgs<ExtArgs>
}, ExtArgs["result"]["familyMembership"]>

export type FamilyMembershipSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  personId?: boolean
  familyUnitId?: boolean
  role?: boolean
  person?: boolean | Prisma.PersonDefaultArgs<ExtArgs>
  familyUnit?: boolean | Prisma.FamilyUnitDefaultArgs<ExtArgs>
}, ExtArgs["result"]["familyMembership"]>

export type FamilyMembershipSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  personId?: boolean
  familyUnitId?: boolean
  role?: boolean
  person?: boolean | Prisma.PersonDefaultArgs<ExtArgs>
  familyUnit?: boolean | Prisma.FamilyUnitDefaultArgs<ExtArgs>
}, ExtArgs["result"]["familyMembership"]>

export type FamilyMembershipSelectScalar = {
  id?: boolean
  personId?: boolean
  familyUnitId?: boolean
  role?: boolean
}

export type FamilyMembershipOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "personId" | "familyUnitId" | "role", ExtArgs["result"]["familyMembership"]>
export type FamilyMembershipInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  person?: boolean | Prisma.PersonDefaultArgs<ExtArgs>
  familyUnit?: boolean | Prisma.FamilyUnitDefaultArgs<ExtArgs>
}
export type FamilyMembershipIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  person?: boolean | Prisma.PersonDefaultArgs<ExtArgs>
  familyUnit?: boolean | Prisma.FamilyUnitDefaultArgs<ExtArgs>
}
export type FamilyMembershipIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  person?: boolean | Prisma.PersonDefaultArgs<ExtArgs>
  familyUnit?: boolean | Prisma.FamilyUnitDefaultArgs<ExtArgs>
}

export type $FamilyMembershipPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FamilyMembership"
  objects: {
    person: Prisma.$PersonPayload<ExtArgs>
    familyUnit: Prisma.$FamilyUnitPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    personId: string
    familyUnitId: string
    role: $Enums.FamilyRole
  }, ExtArgs["result"]["familyMembership"]>
  composites: {}
}

export type FamilyMembershipGetPayload<S extends boolean | null | undefined | FamilyMembershipDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload, S>

export type FamilyMembershipCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FamilyMembershipFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FamilyMembershipCountAggregateInputType | true
  }

export interface FamilyMembershipDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FamilyMembership'], meta: { name: 'FamilyMembership' } }
  /**
   * Find zero or one FamilyMembership that matches the filter.
   * @param {FamilyMembershipFindUniqueArgs} args - Arguments to find a FamilyMembership
   * @example
   * // Get one FamilyMembership
   * const familyMembership = await prisma.familyMembership.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FamilyMembershipFindUniqueArgs>(args: Prisma.SelectSubset<T, FamilyMembershipFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FamilyMembershipClient<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FamilyMembership that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FamilyMembershipFindUniqueOrThrowArgs} args - Arguments to find a FamilyMembership
   * @example
   * // Get one FamilyMembership
   * const familyMembership = await prisma.familyMembership.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FamilyMembershipFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FamilyMembershipFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FamilyMembershipClient<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FamilyMembership that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyMembershipFindFirstArgs} args - Arguments to find a FamilyMembership
   * @example
   * // Get one FamilyMembership
   * const familyMembership = await prisma.familyMembership.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FamilyMembershipFindFirstArgs>(args?: Prisma.SelectSubset<T, FamilyMembershipFindFirstArgs<ExtArgs>>): Prisma.Prisma__FamilyMembershipClient<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FamilyMembership that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyMembershipFindFirstOrThrowArgs} args - Arguments to find a FamilyMembership
   * @example
   * // Get one FamilyMembership
   * const familyMembership = await prisma.familyMembership.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FamilyMembershipFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FamilyMembershipFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FamilyMembershipClient<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FamilyMemberships that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyMembershipFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FamilyMemberships
   * const familyMemberships = await prisma.familyMembership.findMany()
   * 
   * // Get first 10 FamilyMemberships
   * const familyMemberships = await prisma.familyMembership.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const familyMembershipWithIdOnly = await prisma.familyMembership.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FamilyMembershipFindManyArgs>(args?: Prisma.SelectSubset<T, FamilyMembershipFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FamilyMembership.
   * @param {FamilyMembershipCreateArgs} args - Arguments to create a FamilyMembership.
   * @example
   * // Create one FamilyMembership
   * const FamilyMembership = await prisma.familyMembership.create({
   *   data: {
   *     // ... data to create a FamilyMembership
   *   }
   * })
   * 
   */
  create<T extends FamilyMembershipCreateArgs>(args: Prisma.SelectSubset<T, FamilyMembershipCreateArgs<ExtArgs>>): Prisma.Prisma__FamilyMembershipClient<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FamilyMemberships.
   * @param {FamilyMembershipCreateManyArgs} args - Arguments to create many FamilyMemberships.
   * @example
   * // Create many FamilyMemberships
   * const familyMembership = await prisma.familyMembership.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FamilyMembershipCreateManyArgs>(args?: Prisma.SelectSubset<T, FamilyMembershipCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FamilyMemberships and returns the data saved in the database.
   * @param {FamilyMembershipCreateManyAndReturnArgs} args - Arguments to create many FamilyMemberships.
   * @example
   * // Create many FamilyMemberships
   * const familyMembership = await prisma.familyMembership.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FamilyMemberships and only return the `id`
   * const familyMembershipWithIdOnly = await prisma.familyMembership.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FamilyMembershipCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FamilyMembershipCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FamilyMembership.
   * @param {FamilyMembershipDeleteArgs} args - Arguments to delete one FamilyMembership.
   * @example
   * // Delete one FamilyMembership
   * const FamilyMembership = await prisma.familyMembership.delete({
   *   where: {
   *     // ... filter to delete one FamilyMembership
   *   }
   * })
   * 
   */
  delete<T extends FamilyMembershipDeleteArgs>(args: Prisma.SelectSubset<T, FamilyMembershipDeleteArgs<ExtArgs>>): Prisma.Prisma__FamilyMembershipClient<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FamilyMembership.
   * @param {FamilyMembershipUpdateArgs} args - Arguments to update one FamilyMembership.
   * @example
   * // Update one FamilyMembership
   * const familyMembership = await prisma.familyMembership.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FamilyMembershipUpdateArgs>(args: Prisma.SelectSubset<T, FamilyMembershipUpdateArgs<ExtArgs>>): Prisma.Prisma__FamilyMembershipClient<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FamilyMemberships.
   * @param {FamilyMembershipDeleteManyArgs} args - Arguments to filter FamilyMemberships to delete.
   * @example
   * // Delete a few FamilyMemberships
   * const { count } = await prisma.familyMembership.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FamilyMembershipDeleteManyArgs>(args?: Prisma.SelectSubset<T, FamilyMembershipDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FamilyMemberships.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyMembershipUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FamilyMemberships
   * const familyMembership = await prisma.familyMembership.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FamilyMembershipUpdateManyArgs>(args: Prisma.SelectSubset<T, FamilyMembershipUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FamilyMemberships and returns the data updated in the database.
   * @param {FamilyMembershipUpdateManyAndReturnArgs} args - Arguments to update many FamilyMemberships.
   * @example
   * // Update many FamilyMemberships
   * const familyMembership = await prisma.familyMembership.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FamilyMemberships and only return the `id`
   * const familyMembershipWithIdOnly = await prisma.familyMembership.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FamilyMembershipUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FamilyMembershipUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FamilyMembership.
   * @param {FamilyMembershipUpsertArgs} args - Arguments to update or create a FamilyMembership.
   * @example
   * // Update or create a FamilyMembership
   * const familyMembership = await prisma.familyMembership.upsert({
   *   create: {
   *     // ... data to create a FamilyMembership
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FamilyMembership we want to update
   *   }
   * })
   */
  upsert<T extends FamilyMembershipUpsertArgs>(args: Prisma.SelectSubset<T, FamilyMembershipUpsertArgs<ExtArgs>>): Prisma.Prisma__FamilyMembershipClient<runtime.Types.Result.GetResult<Prisma.$FamilyMembershipPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FamilyMemberships.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyMembershipCountArgs} args - Arguments to filter FamilyMemberships to count.
   * @example
   * // Count the number of FamilyMemberships
   * const count = await prisma.familyMembership.count({
   *   where: {
   *     // ... the filter for the FamilyMemberships we want to count
   *   }
   * })
  **/
  count<T extends FamilyMembershipCountArgs>(
    args?: Prisma.Subset<T, FamilyMembershipCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FamilyMembershipCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FamilyMembership.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyMembershipAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FamilyMembershipAggregateArgs>(args: Prisma.Subset<T, FamilyMembershipAggregateArgs>): Prisma.PrismaPromise<GetFamilyMembershipAggregateType<T>>

  /**
   * Group by FamilyMembership.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FamilyMembershipGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FamilyMembershipGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FamilyMembershipGroupByArgs['orderBy'] }
      : { orderBy?: FamilyMembershipGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FamilyMembershipGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFamilyMembershipGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FamilyMembership model
 */
readonly fields: FamilyMembershipFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FamilyMembership.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FamilyMembershipClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  person<T extends Prisma.PersonDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PersonDefaultArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  familyUnit<T extends Prisma.FamilyUnitDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FamilyUnitDefaultArgs<ExtArgs>>): Prisma.Prisma__FamilyUnitClient<runtime.Types.Result.GetResult<Prisma.$FamilyUnitPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FamilyMembership model
 */
export interface FamilyMembershipFieldRefs {
  readonly id: Prisma.FieldRef<"FamilyMembership", 'String'>
  readonly personId: Prisma.FieldRef<"FamilyMembership", 'String'>
  readonly familyUnitId: Prisma.FieldRef<"FamilyMembership", 'String'>
  readonly role: Prisma.FieldRef<"FamilyMembership", 'FamilyRole'>
}
    

// Custom InputTypes
/**
 * FamilyMembership findUnique
 */
export type FamilyMembershipFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
  /**
   * Filter, which FamilyMembership to fetch.
   */
  where: Prisma.FamilyMembershipWhereUniqueInput
}

/**
 * FamilyMembership findUniqueOrThrow
 */
export type FamilyMembershipFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
  /**
   * Filter, which FamilyMembership to fetch.
   */
  where: Prisma.FamilyMembershipWhereUniqueInput
}

/**
 * FamilyMembership findFirst
 */
export type FamilyMembershipFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
  /**
   * Filter, which FamilyMembership to fetch.
   */
  where?: Prisma.FamilyMembershipWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FamilyMemberships to fetch.
   */
  orderBy?: Prisma.FamilyMembershipOrderByWithRelationInput | Prisma.FamilyMembershipOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FamilyMemberships.
   */
  cursor?: Prisma.FamilyMembershipWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FamilyMemberships from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FamilyMemberships.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FamilyMemberships.
   */
  distinct?: Prisma.FamilyMembershipScalarFieldEnum | Prisma.FamilyMembershipScalarFieldEnum[]
}

/**
 * FamilyMembership findFirstOrThrow
 */
export type FamilyMembershipFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
  /**
   * Filter, which FamilyMembership to fetch.
   */
  where?: Prisma.FamilyMembershipWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FamilyMemberships to fetch.
   */
  orderBy?: Prisma.FamilyMembershipOrderByWithRelationInput | Prisma.FamilyMembershipOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FamilyMemberships.
   */
  cursor?: Prisma.FamilyMembershipWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FamilyMemberships from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FamilyMemberships.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FamilyMemberships.
   */
  distinct?: Prisma.FamilyMembershipScalarFieldEnum | Prisma.FamilyMembershipScalarFieldEnum[]
}

/**
 * FamilyMembership findMany
 */
export type FamilyMembershipFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
  /**
   * Filter, which FamilyMemberships to fetch.
   */
  where?: Prisma.FamilyMembershipWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FamilyMemberships to fetch.
   */
  orderBy?: Prisma.FamilyMembershipOrderByWithRelationInput | Prisma.FamilyMembershipOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FamilyMemberships.
   */
  cursor?: Prisma.FamilyMembershipWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FamilyMemberships from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FamilyMemberships.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FamilyMemberships.
   */
  distinct?: Prisma.FamilyMembershipScalarFieldEnum | Prisma.FamilyMembershipScalarFieldEnum[]
}

/**
 * FamilyMembership create
 */
export type FamilyMembershipCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
  /**
   * The data needed to create a FamilyMembership.
   */
  data: Prisma.XOR<Prisma.FamilyMembershipCreateInput, Prisma.FamilyMembershipUncheckedCreateInput>
}

/**
 * FamilyMembership createMany
 */
export type FamilyMembershipCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FamilyMemberships.
   */
  data: Prisma.FamilyMembershipCreateManyInput | Prisma.FamilyMembershipCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FamilyMembership createManyAndReturn
 */
export type FamilyMembershipCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * The data used to create many FamilyMemberships.
   */
  data: Prisma.FamilyMembershipCreateManyInput | Prisma.FamilyMembershipCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FamilyMembership update
 */
export type FamilyMembershipUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
  /**
   * The data needed to update a FamilyMembership.
   */
  data: Prisma.XOR<Prisma.FamilyMembershipUpdateInput, Prisma.FamilyMembershipUncheckedUpdateInput>
  /**
   * Choose, which FamilyMembership to update.
   */
  where: Prisma.FamilyMembershipWhereUniqueInput
}

/**
 * FamilyMembership updateMany
 */
export type FamilyMembershipUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FamilyMemberships.
   */
  data: Prisma.XOR<Prisma.FamilyMembershipUpdateManyMutationInput, Prisma.FamilyMembershipUncheckedUpdateManyInput>
  /**
   * Filter which FamilyMemberships to update
   */
  where?: Prisma.FamilyMembershipWhereInput
  /**
   * Limit how many FamilyMemberships to update.
   */
  limit?: number
}

/**
 * FamilyMembership updateManyAndReturn
 */
export type FamilyMembershipUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * The data used to update FamilyMemberships.
   */
  data: Prisma.XOR<Prisma.FamilyMembershipUpdateManyMutationInput, Prisma.FamilyMembershipUncheckedUpdateManyInput>
  /**
   * Filter which FamilyMemberships to update
   */
  where?: Prisma.FamilyMembershipWhereInput
  /**
   * Limit how many FamilyMemberships to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FamilyMembership upsert
 */
export type FamilyMembershipUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
  /**
   * The filter to search for the FamilyMembership to update in case it exists.
   */
  where: Prisma.FamilyMembershipWhereUniqueInput
  /**
   * In case the FamilyMembership found by the `where` argument doesn't exist, create a new FamilyMembership with this data.
   */
  create: Prisma.XOR<Prisma.FamilyMembershipCreateInput, Prisma.FamilyMembershipUncheckedCreateInput>
  /**
   * In case the FamilyMembership was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FamilyMembershipUpdateInput, Prisma.FamilyMembershipUncheckedUpdateInput>
}

/**
 * FamilyMembership delete
 */
export type FamilyMembershipDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
  /**
   * Filter which FamilyMembership to delete.
   */
  where: Prisma.FamilyMembershipWhereUniqueInput
}

/**
 * FamilyMembership deleteMany
 */
export type FamilyMembershipDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FamilyMemberships to delete
   */
  where?: Prisma.FamilyMembershipWhereInput
  /**
   * Limit how many FamilyMemberships to delete.
   */
  limit?: number
}

/**
 * FamilyMembership without action
 */
export type FamilyMembershipDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FamilyMembership
   */
  select?: Prisma.FamilyMembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FamilyMembership
   */
  omit?: Prisma.FamilyMembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FamilyMembershipInclude<ExtArgs> | null
}
