export const UserErrorCode = {
  DUPLICATE: 'USER_DUPLICATE',
  NOT_FOUND: 'USER_NOT_FOUND',
  ID_INVALID: 'USER_ID_INVALID',
  CREATE_ERROR: 'USER_CREATE_ERROR',
  FIND_ALL_ERROR: 'USER_FINDALL_ERROR',
  FIND_ONE_ERROR: 'USER_FINDONE_ERROR',
  UPDATE_ERROR: 'USER_UPDATE_ERROR',
  REMOVE_ERROR: 'USER_REMOVE_ERROR',
} as const;
