
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model FamilyUnit
 * 
 */
export type FamilyUnit = Prisma.FamilyUnitModel
/**
 * Model FamilyMembership
 * 
 */
export type FamilyMembership = Prisma.FamilyMembershipModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model UserRole
 * 
 */
export type UserRole = Prisma.UserRoleModel
/**
 * Model RolePermission
 * 
 */
export type RolePermission = Prisma.RolePermissionModel
/**
 * Model Audit
 * 
 */
export type Audit = Prisma.AuditModel
/**
 * Model Person
 * 
 */
export type Person = Prisma.PersonModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
